templates/mirrorlist.html
This reworks the html page of the mirrorlist. (etix/mirrorbits#9)
Changes:
- show more information, direct file download links and 'common names' for the mirrors.
- make better usage of the space, especially on larger monitors.
- update the used API for the piechart to 1.1
These changes are live on http://mirrors.kodi.tv/addons/isengard/addons.xml?mirrorlist and can be previewed there.
=> Mirrorlist: rework html page

README.md
We are using Mirrorbits in production since 22nd January 2016.
Thanks for this great software :+1:
=> Update README.md to include OSMC

scan/rsync.go
Some mirrors fail syncing with `... rsync: exit status 23`
After trying to rsync them manually I found the following for some mirrors, `rsync: opendir ".../.~tmp~" (in xbmc) failed: Permission denied (13)`
`.~tmp~` is the default partialdir of rsync, excluding it solved the issue.
It is already running on http://mirrors.kodi.tv, but you can't see any changes on the website.
=> rsync: exclude default partialdir

README.md, config/config.go, contrib/docker/mirrorbits.conf, http/pagerenderer.go, mirrorbits.conf, mirrors/mirrors.go, mirrors/mirrors_test.go, templates/mirrorlist.html
updated version of PR #72 
This switches the mirrorlist-template to use a map based on OSM with leaflet (javascript) instead of a image generated through Googles Maps API.
As the mirrorlist-template was the only place where GMaps was used (the mirrorstatus-template already used OSM), we can now also remove the GoogleMapsAPIKey from the config. The function for generating the URL to the image, GetMirrorMapURL(), isn't needed anymore either, and neither is the test for that function.
=> Switch mirrorlist to use OSM instead of Google Maps

README.md
We're now running Mirrorbits in production at
https://images-dl.endlessm.com/release/?mirrorstats
=> README: add Endless OS

templates/mirrorstats.html
This was added in f7417e4d81f1ab8907a8aa4547ee8d54cba5a3ce but it is
unnecessary. The table has three columns, and each mirror has two rows
in the table. The first row has three cells, the first and last of which
have rowspan=2. So the second row should only have one cell.
=> templates/mirrorstats: remove unnecessary empty <td>

README.md, config/config.go, contrib/localjs/fetchfiles.sh, http/http.go, mirrors/mirrors.go, templates/base.html, templates/mirrorlist.html, templates/mirrorstats.html
This PR makes it convenient to host the Javascript and Fonts used by the default templates locally, so there is no need to use external third-party CDNs that can (and will) track your users.
It consists of
* a script (contrib/localjs/fetchfiles.sh) that will download files into a local directory tree, that can then be served by your webserver (or some 'static.domain.tld' if you have such a thing).
* a new config option 'LocalJSPath' that will insert this path to the locally hosted files in the right places in the templates.
As long as LocalJSPath is not set, the templates will behave as before, loading stuff from Google/cloudflare/bootstrapcdn, because of course, this makes initial setup easier for new users. There are however two unavoidable changes to before in that case, in order to …
=> Better privacy through local hosting of JS and fonts

.travis.yml
See also https://github.com/etix/mirrorbits/issues/84
The `go_import_path` setting allows forks to run Travis builds otherwise it will use the wrong path and [fail like there](https://travis-ci.org/infertux/mirrorbits/jobs/451306327).
=> Test against latest Go versions

README.md
Mirrorbits now powers the mirror director of Parrot OS (Which hosts Caine Linux as well) and we intend to keep it!
=> Add Parrot OS in the "production ready" section

README.md
OSMC still uses MirrorBits and this hasn't changed for several years.
=> Re-instate OSMC as listed project

README.md
Proof: https://images-dl.endlessm.com/release/?mirrorstats
=> README: Endless OS still uses Mirrorbits

README.md
I had to double-check the VLC website as I was surprised you'd still use Freenode. It confirmed my suspicion this text is just outdated and that's how I found VLC developers.
So let's fix the README. ;-)
=> README: fix the IRC server.

cli/commands.go
It was mentioned in issue #125 that it is confusing if mirrors that are disabled are listed as down. Therefore, `mirrorbits list -down` meets user expectations better if it does not list disabled mirrors as down. As a result, the mirror categories disabled and down do no longer intersect.
=> Do not list disabled mirrors as down

contrib/geoip/geoip-lite-update
MaxMind will be requiring HTTPS for all database download requests starting in March 2024.
See [this release note](https://dev.maxmind.com/geoip/release-notes/2023#api-policies---temporary-enforcement-on-october-17-2023).
=> HTTPS required for MaxMind downloads

http/http.go, templates/mirrorlist.html, utils/utils.go
As reported in https://github.com/etix/mirrorbits/issues/114, the mirrorlist page shows information that is rather confusing when a file is 1) present on the local repo but 2) has not been scanned yet.
This commit aims (and hopefully succeeds) at improving the situation.
=> mirrorlist: Better display for files that were not scanned yet

cli/commands.go, config/config.go, go.mod, go.sum, rpc/rpc.go
The main reason to switch (apart from keeping dependencies up-to-date) is the default behaviour for line wrapping. In yaml.v2, the default was line wrapping after 80 characters. In yaml.v3, no line wrapping by default.
For mirrorbits, line wrapping manifests itself in the `show` and `edit` commands. It's an issue, in the sense that it makes it difficult for scripts to interact with those commands, since long values might spread over several lines. For example, parsing the output of `mirrorbits show` with `grep` is error prone because of line wrapping.
This commit bumps the build depencency gopkg.in/yaml from v2 to v3, thus disabling line wrapping in yaml output.
Closes: #153
=> Switch to gopkg.in/yaml.v3

contrib/completions/mirrorbits.bash
The -help flag for those commands was added in
1fe530495bac08e34e0fdae0aa44e54e511f62fb
=> contrib: Update bash completion for commands reload, upgrade and version

main.go
Here's the issue: if ever the LogDir option is modified in the
configuration file, sending SIGHUP is not enough to make the change
effective, and mirrorbits keep using the old LogDir value. In other
words: the LogDir config option is not reloaded on SIGHUP.
How to reproduce: say you have mirrorbits running, and LogDir is
commented out. It means mirrorbits doesn't log downloads under the file
`$LogDir/downloads.log`. Now, edit the configuration, uncomment LogDir,
send SIGHUP to mirrorbits, and observe that it has no effect: there is
still no file `$LogDir/downloads.log`.
I consider it a bug, even though a minor one, just a papercut.
This commit fixes it by always reloading the logs on SIGHUP, thus making
sure that, if ever LogDir was modified, the change is taken into
account.
=> Reload logs on SIGHUP, in case the LogDir option was modified

http/http.go, mirrors/cache_test.go
This MR puts some work in `mirrors/cache_test.go`, there are minor fixes, and two extra tests.
The main outcome is that we now clarify that the function `GetFileInfo` does NOT return `Redis.ErrNil` when the file requested is not found. It doesn't return any error at all, instead it returns a struct with only the field `Path` populated. Note that it was already pretty clear by just looking at the implementation of `GetFileInfo`, but now it's also backed with unit tests.
Based on that, the last commit of this MR drops a useless (and confusing) check for `Redis.ErrNil`.
This work is in preparation of another MR that reworks the moment when `GetFileInfo` is called. It was important to clarify the exact behavior of `GetFileInfo` before being able to to that.
=> Minor fixes and improvements in mirrors/cache_test.go

config/config.go, database/redis.go, http/http.go, mirrorbits.conf
The idea is that if a same machine downloads twice ranges of a given
file within a very short time span, it's probably 1 download (but done
in pieces).
For GIMP, we have particularly such use cases as we also serve torrent
files and use our mirrors as web seeds. So a same torrent client may end
up requesting partial bits of files.
I'm using Redis feature of temporary keys and went with 10 minutes for
expiration. Each time a new piece is requested, the timer is reset. If 2
requests are done with a longer silence frame, let's assume these are
different downloads. The logic is worth what it is, but better than just
re-counting partial downloads within seconds of intervals.
Finally I identify source clients though their (IP, user-agent), hashing
this ID for privacy and not storing …
=> http: avoid counting very close range downloads from a same source.

contrib/mirrorbits-del-stats
Otherwise stats pile up forever, stored in the Redis database, hence eating precious RAM.
In practice, the keys `MIRROR_${date}` and `MIRROR_BYTES_${date}` don't take too much space. Each key is a hash, and the number of items in the hash is the number of mirrors, so that shouldn't be too big.
However, the keys `FILE_${date}` are more problematic. Each key is a hash, but this time the number of items in the hash is the number of files that were served. For big repositories (think Linux distribution for which the repo has between 500k to 1 million files), each daily stat can be quite big, so if we keep it all in the database, in the long-term it will really waste a considerable amount of RAM.
It would be nice if Mirrorbits would provide a command to cleanup the old stats. In the meantime, …
=> Add a contrib script to delete old mirrorbits stats

README.md, http/http.go, http/selection.go
Please see https://github.com/etix/mirrorbits/pull/168 for prior work (ideally merged before this one).
With this MR, we now enable support for the `If-Modified-Since` client header (RFC-7232). A client might request a file only if it modified since a certain date. If it was not, mirrorbits will now return `304` "Not Modified".
This is based on initial work by @ott at https://github.com/etix/mirrorbits/pull/131. This will close https://github.com/etix/mirrorbits/issues/115.
It might make sense to squash all those commits, but I wanted to preserve @ott authorship, and for review it's always easier to have small commits. Feel free to squash during the merge if you prefer.
Clients that use this feature: `apt` for Debian-based Linux distributions. The command `apt update` downloads metadata …
=> Add support for If-Modified-Since (RFC-7232)

contrib/mirrorbits-del-stats
Passing the host to redis-cli is only possible via the "-h" switch, which clashes with the "-h" interpreted as "--help" in the script.
Make "--" stop the argument parsing, so "-h" can be forwarded to redis-cli:
mirrorbits-del-stats daily:30 monthly:12 -- -h redis
=> mirrorbits-del-stats: allow passing the host to redis-cli

cli/commands.go
Currently the command `mirrorbits edit` errors out when the EDITOR environment variable is not set:
```
$ mirrorbits edit mirror.example.com
2024/12/17 14:07:58 Environment variable $EDITOR not set
```
It's not difficult to do better, we can check for the most common text editors. `editor` is checked first, it should be a symlink to the prefered editor on Debian systems (configured by user).
Note that this code was not invented here, it's taken verbatim from incus source code, with thanks.
=> cli: Try harder to find a suitable text editor

contrib/mirrorbits-geoupdate-all
The only way to fix this is to improve the 'mirrorbits geoupdate' command so that it can have a "automatic but conservative" mode.
Ie. the `geoupdate` command should have a way to prompt users only for ASN, Country or Continent change, but apply Latitude and Longitude changes automatically without asking.
Except that it's not clear that every user want that, maybe some would like ASN changes to be applied automatically?
In the meantime, document the issue.
=> mirrorbits-geoupdate-all: Document a bug with this script

config/config.go, http/selection.go, http/selection_test.go, mirrorbits.conf
This PR applies after https://github.com/etix/mirrorbits/pull/186, therefore it will need to be rebased after/if https://github.com/etix/mirrorbits/pull/186 gets merged. Only the 6 last commits really belong to this PR.
No need to review it before https://github.com/etix/mirrorbits/pull/186 gets sorted out.
This PR replaces https://github.com/etix/mirrorbits/pull/147
It fixes https://github.com/etix/mirrorbits/issues/85 for Debian-like distributions. The setting proposed here is kind of minimal, but it should be easy to extend it in the future (ie. match files with regex rather than prefix), if ever a needs arise.
----
The new setting `AllowOutdatedFiles` allows user to define which files are allowed to be outdated on the mirrors, and for how long.
The user defines a list of rules, each …
=> Allow outdated files on mirrors

cli/commands.go
A URL without a scheme is NOT a relative URL.
Unfortunately I used this wrong term in a bunch of commit messages before. Sorry for the confusion.
Fortunately I didn't use the term in any place of the code, except this very comment, so fix it now.
For the avid reader: Wikipedia tells us that we can use the term "Protocol-relative URLs":
> Protocol-relative links (PRL), also known as protocol-relative URLs
> (PRURL), are URLs that have no protocol specified. For example,
> `//example.com` will use the protocol of the current page, typically
> HTTP or HTTPS
However that's not what we use for HTTP+HTTPS mirrors, we use URLs that have only a host and a path. I'm still looking for the right term for that, if any...
=> cli: Fix incorrect comment

logs/logs.go, logs/logs_test.go
The 1st commit is a minor adjustment of what was just merged in https://github.com/etix/mirrorbits/pull/191/, after thinking about it a bit harder (sorry that I didn't get that right at first try).
The other commits rework the code to make it more readable, it's pretty trivial, I couldn't help.
Bonus: 1 new unit test!
=> Downloads logs, adjust format

config/config.go, http/http.go, http/http_test.go, http/selection.go
If the database is not reachable for some reason, mirrorbits must not return "500 Internal Server Error", instead it must redirect users to the fallback mirror(s).
This was broken in https://github.com/etix/mirrorbits/commit/ed1db9e9cadce5fa183b3dae3c7850beb0452455, here's the fix.
The pull request also adds copious unit testing for the http mirror handler.
=> Fix internal server error regressions

http/http.go, http/ifmodifiedsince.go
This code was picked from Golang source code, it's under a different license, and ideally it should be synced with its upstream every now and then.
For all these reasons, it better be in its own file.
For historical background:
- <https://github.com/etix/mirrorbits/pull/131>
- 75e0b5f0413e0af548f19e1e1eef1111549d1f18 and the few commits that follow
=> http: Move If-Modified-Since code in its own file

scan/rsync.go
rsync provides a rsync-ssl script which tries to communicate over tls, on port 874 instead of 873, if it finds openssl/gnutls/stunnel.
In theory we could add a separate cli option for this since there is no official URL scheme for rsync+tls, but to keep things simple for everyone just allow rsyncs:// in rsync URLs.
In case a URL is starting with rsyncs:// we will use rsync-ssl instead of rsync, and rewrite the url back to rsync://.
For testing, here are two public servers that support TLS:
* rsync-ssl rsync://mirrors.dotsrc.org
* rsync-ssl rsync://repo.msys2.org
Using "--contimeout" with rsync-ssl leads to:
"The --contimeout option may only be used when connecting to an rsync daemon."
From my testing "--timeout" aborts though if openssl takes too long to connect, suggesting that it covers …
=> rsync: support rsync-ssl connections too
